# Generated by Django 3.2.3 on 2021-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210527_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.TextField(choices=[('green', 'green'), ('purple', 'purple'), ('orange', 'orange')], default='green'),
            preserve_default=False,
        ),
    ]
