# Generated by Django 3.2.3 on 2021-06-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-pk']},
        ),
    ]
